import requests


def raise_api_error(function_name: str, status_code, reason):
    """
    Helper function for issuing warnings from failed API calls
    :param function_name: Name of the function that calls this function
    :param status_code: Status code returned from requests call
    :param reason: Reason retured from request call
    """
    raise requests.RequestException(f"Failed API Call in '{function_name}'.\n"
          f"API response code: {status_code}\n"
          f"API error reason: {reason}")


def get_all_app_ids_and_names(print_endpoint: bool=False):
    """
    Get a list of every app id and name.
    :return: A list of dictionaries containing every app id and corresponding app name. The dictionaries have two
    keys: 'appid' and 'name'.
    """
    # Make api request
    response = requests.get("https://api.steampowered.com/ISteamApps/GetAppList/v2/")
    if print_endpoint:
        print(response.url)

    # Check status
    if response.status_code != 200:
        raise_api_error("get_all_app_ids_and_names", response.status_code, response.reason)

    # Return resulting list
    return response.json()["applist"]["apps"]


def get_app_details(appid: str or int, print_endpoint: bool=False):
    """
    Get the details about a single app
    See https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-App-Details for more information.
    :param appid: A single Steam AppID as an integer or a string
    :param print_endpoint: if True, print the API endpoint used in the request
    :return: App details in JSON format
    """
    # Set parameters, make api call, and optionally print the endpoing
    parameters = {"appids": appid}
    response = requests.get("https://store.steampowered.com/api/appdetails", params=parameters)
    if print_endpoint:
        print(response.url)

    # Throw error if the status code is not 200
    if response.status_code != 200:
        raise_api_error("get_app_details", response.status_code, response.reason)

    # Return the JSON information
    return response.json()


def get_app_reviews(appid: str or int, print_endpoint: bool=False):
    """
    Get the reviews for a single app.
    See https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-App-Reviews
    :param appid: A single Steam AppID as an integer or a string
    :param print_endpoint: if True, print the API endpoint used in the request
    :return: App details in JSON format
    """
    # Get the response and optionally print the full API endpoint
    response = requests.get(f"https://store.steampowered.com/appreviews/{appid}?json=1")
    if print_endpoint:
        print(response.url)

    # Check status code. Raise error if status code is not 200
    if response.status_code != 200:
        raise_api_error("get_app_reviews", response.status_code, response.reason)

    # Return JSON
    return response.json()


def get_steam_app_id(app_name, steam_apps):
    """
    Get a Steam app ID from a Steam app name
    :param app_name: The name of the app
    :param steam_apps: A list of steam apps. Most likely this was generated by the function 'get_all_app_ids_and_names'.
    :return: The corresponding Steam app ID as an integer.
    """
    app_id = None
    for app in steam_apps:
        if app["name"].lower() != app_name.lower():
            continue
        else:
            app_id = app["appid"]
            break

    if app_id is not None:
        return app_id

    raise RuntimeError("No corresponding app id could be found. Please check the spelling of the Steam App name and "
                       "try again.")
